============================= test session starts ==============================
platform linux -- Python 3.7.6, pytest-5.3.5, py-1.8.1, pluggy-0.13.1
rootdir: /home/ordabayev/Documents/pyro, inifile: setup.cfg
collected 129 items

tests/test_examples.py ...F.................................F........F.. [ 37%]
...F.........X.....................F........F.......F..xxxx......F.xxxx. [ 93%]
..x.....                                                                 [100%]

=================================== FAILURES ===================================
__ test_cpu[baseball.py --num-samples=200 --warmup-steps=100 --num-chains=2] ___

example = ['baseball.py', '--num-samples=200', '--warmup-steps=100', '--num-chains=2']

    @pytest.mark.parametrize('example', CPU_EXAMPLES)
    def test_cpu(example):
        logger.info('Running:\npython examples/{}'.format(example))
        example = example.split()
        filename, args = example[0], example[1:]
        filename = os.path.join(EXAMPLES_DIR, filename)
>       check_call([sys.executable, filename] + args)

tests/test_examples.py:189: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/baseball.py', '--num-samples=200', '--warmup-steps=100', '--num-chains=2'],)
kwargs = {}, retcode = 1
cmd = ['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/baseball.py', '--num-samples=200', '--warmup-steps=100', '--num-chains=2']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/baseball.py', '--num-samples=200', '--warmup-steps=100', '--num-chains=2']' returned non-zero exit status 1.

../../anaconda3/envs/dice/lib/python3.7/subprocess.py:363: CalledProcessError
----------------------------- Captured stderr call -----------------------------
I 	 Running:
python examples/baseball.py --num-samples=200 --warmup-steps=100 --num-chains=2
Original Dataset:
   FirstName    LastName  At-Bats  ...  SeasonAt-Bats  SeasonHits  SeasonAverage
0    Roberto    Clemente       45  ...            412         145          0.352
1      Frank    Robinson       45  ...            471         144          0.306
2      Frank      Howard       45  ...            566         160          0.283
3        Jay   Johnstone       45  ...            320          76          0.238
4        Ken       Berry       45  ...            463         128          0.276
5        Jim     Spencer       45  ...            511         140          0.274
6        Don   Kessinger       45  ...            631         168          0.266
7       Luis    Alvarado       45  ...            183          41          0.224
8        Ron       Santo       45  ...            555         148          0.267
9        Ron     Swaboda       45  ...            245          57          0.233
10      Rico  Petrocelli       45  ...            583         152          0.261
11     Ellie   Rodriguez       45  ...            231          52          0.225
12    George       Scott       45  ...            480         142          0.296
13       Del       Unser       45  ...            322          83          0.258
14     Billy    Williams       45  ...            636         205          0.251
15      Bert  Campaneris       45  ...            603         168          0.279
16   Thurman      Munson       45  ...            453         137          0.302
17       Max       Alvis       45  ...            115          21          0.183

[18 rows x 10 columns]
Warmup [1]:   0%|          | 0/300 [00:00, ?it/s]
Warmup [2]:   0%|          | 0/300 [00:00, ?it/s][Atorch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
Warmup [1]:   0%|          | 0/300 [00:00, ?it/s]
Warmup [2]:   0%|          | 0/300 [00:00, ?it/s]


Traceback (most recent call last):
  File "/home/ordabayev/Documents/pyro/examples/baseball.py", line 360, in <module>
    main(args)
  File "/home/ordabayev/Documents/pyro/examples/baseball.py", line 250, in main
    mcmc.run(at_bats, hits)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/mcmc/api.py", line 357, in run
    for x, chain_id in self.sampler.run(*args, **kwargs):
  File "/home/ordabayev/Documents/pyro/pyro/infer/mcmc/api.py", line 236, in run
    w.start()
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 324, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: error executing torch_shm_manager at "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at /pytorch/torch/lib/libshm/core.cpp:99
------------------------------ Captured log call -------------------------------
INFO     tests.test_examples:test_examples.py:185 Running:
python examples/baseball.py --num-samples=200 --warmup-steps=100 --num-chains=2
____________ test_cpu[hmm.py --num-steps=1 --truncate=10 --model=5] ____________

example = ['hmm.py', '--num-steps=1', '--truncate=10', '--model=5']

    @pytest.mark.parametrize('example', CPU_EXAMPLES)
    def test_cpu(example):
        logger.info('Running:\npython examples/{}'.format(example))
        example = example.split()
        filename, args = example[0], example[1:]
        filename = os.path.join(EXAMPLES_DIR, filename)
>       check_call([sys.executable, filename] + args)

tests/test_examples.py:189: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5'],)
kwargs = {}, retcode = 1
cmd = ['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5']' returned non-zero exit status 1.

../../anaconda3/envs/dice/lib/python3.7/subprocess.py:363: CalledProcessError
----------------------------- Captured stderr call -----------------------------
I 	 Running:
python examples/hmm.py --num-steps=1 --truncate=10 --model=5
      606 Loading data
      668 ----------------------------------------
      669 Training model_5 on 229 sequences
      677 Step	Loss
Traceback (most recent call last):
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 665, in <module>
    main(args)
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 607, in main
    loss = svi.step(sequences, lengths, args=args, batch_size=args.batch_size)
  File "/home/ordabayev/Documents/pyro/pyro/infer/svi.py", line 128, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 399, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 342, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 295, in _get_trace
    "flat", self.max_plate_nesting, model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/enum.py", line 44, in get_importance_trace
    guide_trace = poutine.trace(guide, graph_type=graph_type).get_trace(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/handlers.py", line 172, in _fn
    return ftr(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/nn/module.py", line 289, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 326, in forward
    self._setup_prototype(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 310, in _setup_prototype
    super()._setup_prototype(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 133, in _setup_prototype
    self.prototype_trace = poutine.block(poutine.trace(model).get_trace)(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 436, in model_5
    with pyro.plate("tones_{}".format(t), data_dim, dim=-1):
  File "/home/ordabayev/Documents/pyro/pyro/poutine/subsample_messenger.py", line 78, in __init__
    self._indices, self.use_cuda, self.device)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/subsample_messenger.py", line 107, in _subsample
    apply_stack(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/runtime.py", line 193, in apply_stack
    frame._process_message(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/mask_messenger.py", line 38, in _process_message
    msg["fn"] = msg["fn"].mask(msg["mask"])
AttributeError: '_Subsample' object has no attribute 'mask'
------------------------------ Captured log call -------------------------------
INFO     tests.test_examples:test_examples.py:185 Running:
python examples/hmm.py --num-steps=1 --truncate=10 --model=5
_ test_cpu[hmm.py --num-steps=1 --truncate=10 --model=5 --tmc --tmc-num-samples=2] _

example = ['hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--tmc', '--tmc-num-samples=2']

    @pytest.mark.parametrize('example', CPU_EXAMPLES)
    def test_cpu(example):
        logger.info('Running:\npython examples/{}'.format(example))
        example = example.split()
        filename, args = example[0], example[1:]
        filename = os.path.join(EXAMPLES_DIR, filename)
>       check_call([sys.executable, filename] + args)

tests/test_examples.py:189: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--tmc', ...],)
kwargs = {}, retcode = 1
cmd = ['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--tmc', ...]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--tmc', '--tmc-num-samples=2']' returned non-zero exit status 1.

../../anaconda3/envs/dice/lib/python3.7/subprocess.py:363: CalledProcessError
----------------------------- Captured stderr call -----------------------------
I 	 Running:
python examples/hmm.py --num-steps=1 --truncate=10 --model=5 --tmc --tmc-num-samples=2
      598 Loading data
      659 ----------------------------------------
      660 Training model_5 on 229 sequences
      669 Step	Loss
Traceback (most recent call last):
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 665, in <module>
    main(args)
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 607, in main
    loss = svi.step(sequences, lengths, args=args, batch_size=args.batch_size)
  File "/home/ordabayev/Documents/pyro/pyro/infer/svi.py", line 128, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/tracetmc_elbo.py", line 207, in loss_and_grads
    loss = self.differentiable_loss(model, guide, *args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/tracetmc_elbo.py", line 187, in differentiable_loss
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/home/ordabayev/Documents/pyro/pyro/infer/tracetmc_elbo.py", line 173, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/tracetmc_elbo.py", line 126, in _get_trace
    "flat", self.max_plate_nesting, model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/enum.py", line 44, in get_importance_trace
    guide_trace = poutine.trace(guide, graph_type=graph_type).get_trace(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/handlers.py", line 172, in _fn
    return ftr(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/nn/module.py", line 289, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 326, in forward
    self._setup_prototype(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 310, in _setup_prototype
    super()._setup_prototype(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 133, in _setup_prototype
    self.prototype_trace = poutine.block(poutine.trace(model).get_trace)(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 436, in model_5
    with pyro.plate("tones_{}".format(t), data_dim, dim=-1):
  File "/home/ordabayev/Documents/pyro/pyro/poutine/subsample_messenger.py", line 78, in __init__
    self._indices, self.use_cuda, self.device)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/subsample_messenger.py", line 107, in _subsample
    apply_stack(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/runtime.py", line 193, in apply_stack
    frame._process_message(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/mask_messenger.py", line 38, in _process_message
    msg["fn"] = msg["fn"].mask(msg["mask"])
AttributeError: '_Subsample' object has no attribute 'mask'
------------------------------ Captured log call -------------------------------
INFO     tests.test_examples:test_examples.py:185 Running:
python examples/hmm.py --num-steps=1 --truncate=10 --model=5 --tmc --tmc-num-samples=2
_______________ test_cpu[mixed_hmm/experiment.py --timesteps=1] ________________

example = ['mixed_hmm/experiment.py', '--timesteps=1']

    @pytest.mark.parametrize('example', CPU_EXAMPLES)
    def test_cpu(example):
        logger.info('Running:\npython examples/{}'.format(example))
        example = example.split()
        filename, args = example[0], example[1:]
        filename = os.path.join(EXAMPLES_DIR, filename)
>       check_call([sys.executable, filename] + args)

tests/test_examples.py:189: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/mixed_hmm/experiment.py', '--timesteps=1'],)
kwargs = {}, retcode = 1
cmd = ['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/mixed_hmm/experiment.py', '--timesteps=1']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/mixed_hmm/experiment.py', '--timesteps=1']' returned non-zero exit status 1.

../../anaconda3/envs/dice/lib/python3.7/subprocess.py:363: CalledProcessError
----------------------------- Captured stderr call -----------------------------
I 	 Running:
python examples/mixed_hmm/experiment.py --timesteps=1
Traceback (most recent call last):
  File "/home/ordabayev/Documents/pyro/examples/mixed_hmm/experiment.py", line 160, in <module>
    run_expt(vars(args))
  File "/home/ordabayev/Documents/pyro/examples/mixed_hmm/experiment.py", line 59, in run_expt
    num_parameters = aic_num_parameters(model, guide)
  File "/home/ordabayev/Documents/pyro/examples/mixed_hmm/experiment.py", line 33, in aic_num_parameters
    TraceEnum_ELBO(max_plate_nesting=2).differentiable_loss(model, guide)
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 375, in differentiable_loss
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 342, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 295, in _get_trace
    "flat", self.max_plate_nesting, model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/enum.py", line 48, in get_importance_trace
    graph_type=graph_type).get_trace(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/examples/mixed_hmm/model.py", line 167, in model_generic
    obs=config["observations"]["step"][..., t])
  File "/home/ordabayev/Documents/pyro/pyro/primitives.py", line 113, in sample
    apply_stack(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/runtime.py", line 193, in apply_stack
    frame._process_message(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/mask_messenger.py", line 38, in _process_message
    msg["fn"] = msg["fn"].mask(msg["mask"])
TypeError: 'Tensor' object is not callable
------------------------------ Captured log call -------------------------------
INFO     tests.test_examples:test_examples.py:185 Running:
python examples/mixed_hmm/experiment.py --timesteps=1
________ test_cuda[hmm.py --num-steps=1 --truncate=10 --model=5 --cuda] ________

example = ['hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--cuda']

    @requires_cuda
    @pytest.mark.parametrize('example', CUDA_EXAMPLES)
    def test_cuda(example):
        logger.info('Running:\npython examples/{}'.format(example))
        example = example.split()
        filename, args = example[0], example[1:]
        filename = os.path.join(EXAMPLES_DIR, filename)
>       check_call([sys.executable, filename] + args)

tests/test_examples.py:199: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--cuda'],)
kwargs = {}, retcode = 1
cmd = ['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--cuda']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--cuda']' returned non-zero exit status 1.

../../anaconda3/envs/dice/lib/python3.7/subprocess.py:363: CalledProcessError
----------------------------- Captured stderr call -----------------------------
I 	 Running:
python examples/hmm.py --num-steps=1 --truncate=10 --model=5 --cuda
      609 Loading data
     4978 ----------------------------------------
     4978 Training model_5 on 229 sequences
     4980 Step	Loss
Traceback (most recent call last):
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 665, in <module>
    main(args)
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 607, in main
    loss = svi.step(sequences, lengths, args=args, batch_size=args.batch_size)
  File "/home/ordabayev/Documents/pyro/pyro/infer/svi.py", line 128, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 399, in loss_and_grads
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 342, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 295, in _get_trace
    "flat", self.max_plate_nesting, model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/enum.py", line 44, in get_importance_trace
    guide_trace = poutine.trace(guide, graph_type=graph_type).get_trace(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/handlers.py", line 172, in _fn
    return ftr(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/nn/module.py", line 289, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 326, in forward
    self._setup_prototype(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 310, in _setup_prototype
    super()._setup_prototype(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 133, in _setup_prototype
    self.prototype_trace = poutine.block(poutine.trace(model).get_trace)(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 436, in model_5
    with pyro.plate("tones_{}".format(t), data_dim, dim=-1):
  File "/home/ordabayev/Documents/pyro/pyro/poutine/subsample_messenger.py", line 78, in __init__
    self._indices, self.use_cuda, self.device)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/subsample_messenger.py", line 107, in _subsample
    apply_stack(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/runtime.py", line 193, in apply_stack
    frame._process_message(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/mask_messenger.py", line 38, in _process_message
    msg["fn"] = msg["fn"].mask(msg["mask"])
AttributeError: '_Subsample' object has no attribute 'mask'
------------------------------ Captured log call -------------------------------
INFO     tests.test_examples:test_examples.py:195 Running:
python examples/hmm.py --num-steps=1 --truncate=10 --model=5 --cuda
_ test_cuda[hmm.py --num-steps=1 --truncate=10 --model=5 --tmc --tmc-num-samples=2 --cuda] _

example = ['hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--tmc', '--tmc-num-samples=2', ...]

    @requires_cuda
    @pytest.mark.parametrize('example', CUDA_EXAMPLES)
    def test_cuda(example):
        logger.info('Running:\npython examples/{}'.format(example))
        example = example.split()
        filename, args = example[0], example[1:]
        filename = os.path.join(EXAMPLES_DIR, filename)
>       check_call([sys.executable, filename] + args)

tests/test_examples.py:199: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--tmc', ...],)
kwargs = {}, retcode = 1
cmd = ['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--tmc', ...]

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--tmc', '--tmc-num-samples=2', '--cuda']' returned non-zero exit status 1.

../../anaconda3/envs/dice/lib/python3.7/subprocess.py:363: CalledProcessError
----------------------------- Captured stderr call -----------------------------
I 	 Running:
python examples/hmm.py --num-steps=1 --truncate=10 --model=5 --tmc --tmc-num-samples=2 --cuda
      609 Loading data
     4958 ----------------------------------------
     4958 Training model_5 on 229 sequences
     4960 Step	Loss
Traceback (most recent call last):
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 665, in <module>
    main(args)
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 607, in main
    loss = svi.step(sequences, lengths, args=args, batch_size=args.batch_size)
  File "/home/ordabayev/Documents/pyro/pyro/infer/svi.py", line 128, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/tracetmc_elbo.py", line 207, in loss_and_grads
    loss = self.differentiable_loss(model, guide, *args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/tracetmc_elbo.py", line 187, in differentiable_loss
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/home/ordabayev/Documents/pyro/pyro/infer/tracetmc_elbo.py", line 173, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/tracetmc_elbo.py", line 126, in _get_trace
    "flat", self.max_plate_nesting, model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/enum.py", line 44, in get_importance_trace
    guide_trace = poutine.trace(guide, graph_type=graph_type).get_trace(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/handlers.py", line 172, in _fn
    return ftr(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/nn/module.py", line 289, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 326, in forward
    self._setup_prototype(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 310, in _setup_prototype
    super()._setup_prototype(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 133, in _setup_prototype
    self.prototype_trace = poutine.block(poutine.trace(model).get_trace)(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 436, in model_5
    with pyro.plate("tones_{}".format(t), data_dim, dim=-1):
  File "/home/ordabayev/Documents/pyro/pyro/poutine/subsample_messenger.py", line 78, in __init__
    self._indices, self.use_cuda, self.device)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/subsample_messenger.py", line 107, in _subsample
    apply_stack(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/runtime.py", line 193, in apply_stack
    frame._process_message(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/mask_messenger.py", line 38, in _process_message
    msg["fn"] = msg["fn"].mask(msg["mask"])
AttributeError: '_Subsample' object has no attribute 'mask'
------------------------------ Captured log call -------------------------------
INFO     tests.test_examples:test_examples.py:195 Running:
python examples/hmm.py --num-steps=1 --truncate=10 --model=5 --tmc --tmc-num-samples=2 --cuda
_______ test_jit[baseball.py --num-samples=200 --warmup-steps=100 --jit] _______

example = ['baseball.py', '--num-samples=200', '--warmup-steps=100', '--jit']

    @pytest.mark.parametrize('example', JIT_EXAMPLES)
    def test_jit(example):
        logger.info('Running:\npython examples/{}'.format(example))
        example = example.split()
        filename, args = example[0], example[1:]
        filename = os.path.join(EXAMPLES_DIR, filename)
>       check_call([sys.executable, filename] + args)

tests/test_examples.py:208: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/baseball.py', '--num-samples=200', '--warmup-steps=100', '--jit'],)
kwargs = {}, retcode = 1
cmd = ['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/baseball.py', '--num-samples=200', '--warmup-steps=100', '--jit']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/baseball.py', '--num-samples=200', '--warmup-steps=100', '--jit']' returned non-zero exit status 1.

../../anaconda3/envs/dice/lib/python3.7/subprocess.py:363: CalledProcessError
----------------------------- Captured stderr call -----------------------------
I 	 Running:
python examples/baseball.py --num-samples=200 --warmup-steps=100 --jit
Original Dataset:
   FirstName    LastName  At-Bats  ...  SeasonAt-Bats  SeasonHits  SeasonAverage
0    Roberto    Clemente       45  ...            412         145          0.352
1      Frank    Robinson       45  ...            471         144          0.306
2      Frank      Howard       45  ...            566         160          0.283
3        Jay   Johnstone       45  ...            320          76          0.238
4        Ken       Berry       45  ...            463         128          0.276
5        Jim     Spencer       45  ...            511         140          0.274
6        Don   Kessinger       45  ...            631         168          0.266
7       Luis    Alvarado       45  ...            183          41          0.224
8        Ron       Santo       45  ...            555         148          0.267
9        Ron     Swaboda       45  ...            245          57          0.233
10      Rico  Petrocelli       45  ...            583         152          0.261
11     Ellie   Rodriguez       45  ...            231          52          0.225
12    George       Scott       45  ...            480         142          0.296
13       Del       Unser       45  ...            322          83          0.258
14     Billy    Williams       45  ...            636         205          0.251
15      Bert  Campaneris       45  ...            603         168          0.279
16   Thurman      Munson       45  ...            453         137          0.302
17       Max       Alvis       45  ...            115          21          0.183

[18 rows x 10 columns]
Warmup [1]:   0%|          | 0/300 [00:00, ?it/s]
Warmup [2]:   0%|          | 0/300 [00:00, ?it/s][A

Warmup [3]:   0%|          | 0/300 [00:00, ?it/s][A[A


Warmup [4]:   0%|          | 0/300 [00:00, ?it/s][A[A[Atorch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
Warmup [1]:   0%|          | 0/300 [00:00, ?it/s]
Warmup [2]:   0%|          | 0/300 [00:00, ?it/s]
Warmup [3]:   0%|          | 0/300 [00:00, ?it/s]
Warmup [4]:   0%|          | 0/300 [00:00, ?it/s]




Traceback (most recent call last):
  File "/home/ordabayev/Documents/pyro/examples/baseball.py", line 360, in <module>
    main(args)
  File "/home/ordabayev/Documents/pyro/examples/baseball.py", line 250, in main
    mcmc.run(at_bats, hits)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/mcmc/api.py", line 357, in run
    for x, chain_id in self.sampler.run(*args, **kwargs):
  File "/home/ordabayev/Documents/pyro/pyro/infer/mcmc/api.py", line 236, in run
    w.start()
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 324, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: error executing torch_shm_manager at "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at /pytorch/torch/lib/libshm/core.cpp:99
------------------------------ Captured log call -------------------------------
INFO     tests.test_examples:test_examples.py:204 Running:
python examples/baseball.py --num-samples=200 --warmup-steps=100 --jit
_________ test_jit[hmm.py --num-steps=1 --truncate=10 --model=5 --jit] _________

example = ['hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--jit']

    @pytest.mark.parametrize('example', JIT_EXAMPLES)
    def test_jit(example):
        logger.info('Running:\npython examples/{}'.format(example))
        example = example.split()
        filename, args = example[0], example[1:]
        filename = os.path.join(EXAMPLES_DIR, filename)
>       check_call([sys.executable, filename] + args)

tests/test_examples.py:208: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

popenargs = (['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--jit'],)
kwargs = {}, retcode = 1
cmd = ['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--jit']

    def check_call(*popenargs, **kwargs):
        """Run command with arguments.  Wait for command to complete.  If
        the exit code was zero then return, otherwise raise
        CalledProcessError.  The CalledProcessError object will have the
        return code in the returncode attribute.
    
        The arguments are the same as for the call function.  Example:
    
        check_call(["ls", "-l"])
        """
        retcode = call(*popenargs, **kwargs)
        if retcode:
            cmd = kwargs.get("args")
            if cmd is None:
                cmd = popenargs[0]
>           raise CalledProcessError(retcode, cmd)
E           subprocess.CalledProcessError: Command '['/home/ordabayev/anaconda3/envs/dice/bin/python', '/home/ordabayev/Documents/pyro/examples/hmm.py', '--num-steps=1', '--truncate=10', '--model=5', '--jit']' returned non-zero exit status 1.

../../anaconda3/envs/dice/lib/python3.7/subprocess.py:363: CalledProcessError
----------------------------- Captured stderr call -----------------------------
I 	 Running:
python examples/hmm.py --num-steps=1 --truncate=10 --model=5 --jit
      605 Loading data
      665 ----------------------------------------
      666 Training model_5 on 229 sequences
      674 Step	Loss
Traceback (most recent call last):
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 665, in <module>
    main(args)
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 607, in main
    loss = svi.step(sequences, lengths, args=args, batch_size=args.batch_size)
  File "/home/ordabayev/Documents/pyro/pyro/infer/svi.py", line 128, in step
    loss = self.loss_and_grads(self.model, self.guide, *args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 496, in loss_and_grads
    differentiable_loss = self.differentiable_loss(model, guide, *args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 493, in differentiable_loss
    return self._differentiable_loss(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/ops/jit.py", line 71, in __call__
    self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 487, in differentiable_loss
    for model_trace, guide_trace in self._get_traces(model, guide, args, kwargs):
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 342, in _get_traces
    yield self._get_trace(model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/traceenum_elbo.py", line 295, in _get_trace
    "flat", self.max_plate_nesting, model, guide, args, kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/enum.py", line 44, in get_importance_trace
    guide_trace = poutine.trace(guide, graph_type=graph_type).get_trace(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/handlers.py", line 172, in _fn
    return ftr(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/nn/module.py", line 289, in __call__
    return super().__call__(*args, **kwargs)
  File "/home/ordabayev/anaconda3/envs/dice/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 326, in forward
    self._setup_prototype(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 310, in _setup_prototype
    super()._setup_prototype(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/infer/autoguide/guides.py", line 133, in _setup_prototype
    self.prototype_trace = poutine.block(poutine.trace(model).get_trace)(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 185, in get_trace
    self(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/trace_messenger.py", line 165, in __call__
    ret = self.fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/messenger.py", line 11, in _context_wrap
    return fn(*args, **kwargs)
  File "/home/ordabayev/Documents/pyro/examples/hmm.py", line 436, in model_5
    with pyro.plate("tones_{}".format(t), data_dim, dim=-1):
  File "/home/ordabayev/Documents/pyro/pyro/poutine/subsample_messenger.py", line 78, in __init__
    self._indices, self.use_cuda, self.device)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/subsample_messenger.py", line 107, in _subsample
    apply_stack(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/runtime.py", line 193, in apply_stack
    frame._process_message(msg)
  File "/home/ordabayev/Documents/pyro/pyro/poutine/mask_messenger.py", line 38, in _process_message
    msg["fn"] = msg["fn"].mask(msg["mask"])
AttributeError: '_Subsample' object has no attribute 'mask'
------------------------------ Captured log call -------------------------------
INFO     tests.test_examples:test_examples.py:204 Running:
python examples/hmm.py --num-steps=1 --truncate=10 --model=5 --jit
======= 8 failed, 111 passed, 9 xfailed, 1 xpassed in 2535.53s (0:42:15) =======
